Algoritmo "EntradaDeDados"

Var
idade : inteiro
salario1, salario2 : real
nome : caractere


Inicio
escreval("Digite seu nome:")
leia(nome)
escreval("Digite sua idade:")
leia(idade)
escreval("Quanto você ganhou nos ultimos dois meses:")
leia(salario1, salario2)

escreval

escreval("DADOS DIGITADOS:")
escreval("Nome: ", nome)
escreval("Idade: ", idade)
escreval("Salario 1: R$ ", salario1:8:2)
escreval("Salario 2: R$ ", salario2:8:2)

Fimalgoritmo