Algoritmo "ExerciciosParte1-Notas"
Var

     nota1, nota2, notaFinal, media: real

Inicio
      media <- 60.00

      escreval("Digite a primeira nota:")
      leia(nota1)
      escreval("Digite a segunda nota:")
      leia(nota2)
      
      escreval

      notaFinal <- nota1 + nota2;
      
      escreval("Nota final: ", notaFinal)
      
      se notaFinal < media entao
         escreva("Reprovado")
      fimse




Fimalgoritmo