Algoritmo "ExerciciosParte2-MediaPonderada"
Var

     n, i : inteiro
     x, y, z, media : real

Inicio


   escreval("Quantos casos voce vai diitar? ")
   leia(n)
h
   para i de 1 ate n faca

      escreval("Digite tres numeros: ")
      leia(x)
      leia(y)
      leia(z)

      media <- ((x * 2) + (y * 3) + (z * 5))/ 10
      
      escreval("Media: ", media:6:1)

   fimpara



Fimalgoritmo