Algoritmo "ExerciciosParte1-Aumento"
Var

       salarioAtual, aumento, novoSalario : real
       porcentagem : inteiro
Inicio

      escreval("Digite o salario da pessoa: ")
      leia(salarioAtual)



      se salarioAtual <= 1000.00 entao
         porcentagem <- 20
      senao
           se salarioAtual <= 3000.00 entao
           porcentagem <- 15
           senao
                se salarioAtual <= 8000.00 entao
                porcentagem <- 10
                senao
                porcentagem <- 5
                fimse
           fimse
      fimse
      
      

      se (salarioAtual <= 1000.00) entao
         aumento <- salarioAtual * porcentagem / 100
         novosalario <- salarioAtual + aumento
         escreval("Novo salario: ", novoSalario)
         escreval("Aumento: ", aumento)
         escreva("Porcentagem: ", porcentagem)
      senao
           se (salarioAtual <= 3000.00) entao
           aumento <- salarioAtual * porcentagem / 100
           novosalario <- salarioAtual + aumento
           escreval("Novo salario: ", novoSalario)
           escreval("Aumento: ", aumento)
           escreva("Porcentagem: ", porcentagem, " %")
           senao
                se salario <= 8000.00 ENTAO
                aumento <- salarioAtual * porcentagem / 100
                novosalario <- salarioAtual + aumento
                escreval("Novo salario: ", novoSalario)
                escreval("Aumento: ", aumento)
                escreva("Porcentagem: ", porcentagem, " %")
                senao
                   escreval("Novo salario: ", novoSalario)
                   escreval("Aumento: ", aumento)
                   escreva("Porcentagem: ", porcentagem, " %")
                fimse
           
      


Fimalgoritmo