Algoritmo "ExerciciosParte1-Crescente"
Var

    x, y : inteiro

Inicio

//       decrescente <- x > y
//      crescente <- x < y
      
      escreval("Digite dois valores: ")
      leia(x)
      leia(y)
      
      enquanto x <> y faca
               se x > y entao
                  escreval("Decrescente")
                  senao
                  escreval("Crescente")
               fimse
               
               escreval("Digite outros dois numeros: ")
               leia(x)
               leia(y)
      fimenquanto




Fimalgoritmo