Algoritmo "Para"
Var

    i, n, soma, x : inteiro

Inicio

      soma <- 0

        escreval("Quantos numeros serão digitados? ")
        leia(n)
        

        
        para i de 1       ate n faca
               escreval("Digite um numero: ")
               leia(x)
               
               soma <- x + soma
        fimpara
        
        escreval("Soma: ", soma)

      
Fimalgoritmo