Algoritmo "AulaDeLogica"


Var
 //a : inteiro
 //b : real
 //c : caractere
 //d : logico
  
 idade : inteiro
 salario : real
 nome : caractere
 
Inicio
//escreva ("Ola mundo!") ////Não quebra a escrita
//escreval ("Ola mundo!")   //// Quebra a escrita
//escreva ("Ola mundo!")

//Add valor a variavel
//a <- 32
//b <- 2.3254
//c <- "Bom dia!"
//d <- VERDADEIRO

//escreval (a)
//escreval (b)
//escreval (b:10) ////Add 10 espaços
//escreval (b:10:2) ////Da 10 espaços e imprime 2 casas depois da virgula
//escreval (c)
//escreval (d)

//Add valor as variaveis
idade <- 20
salario <- 4500.9
nome <- "Marcela"

escreval (nome, " tem", idade, " anos e ganha", salario )

Fimalgoritmo